[package]
name = "kaspa-vanity"
version = "0.1.0"
edition = "2021"

[dependencies]
kaspa-wallet-keys = "0.15.0"
kaspa-addresses   = "0.15.0"
secp256k1         = "0.29.0"       # secp256k1 for key generation & compression
rayon             = "1.7"
hex = "0.4.3"
serde_json = "1.0.140"